name: soultosoul
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.8.4+3
  flutter_walkthrough: ^0.0.1
  animated_text_kit: ^1.3.0
  google_sign_in: ^4.0.1+3
  firebase_core: ^0.3.4
  font_awesome_flutter:
  cloud_firestore: ^0.9.13+1
  fluttertoast: ^3.1.3
  flutter_sticky_header: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

